version: '3.0'

services:
  angular:
    build: front-end/Angular6
    image: frontend
    ports:
      - "80:80"

  node:
    build: back-end/Project
    image: backend
    ports:
      - "3000:3000"

  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
